// @vitest-environment happy-dom
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { contextForRange, extractPage, firstSentence, ownHosts, rangeFor } from "../src/lib/extract";

// happy-dom binds every Range to the window's document, so fixtures are loaded into it rather than a parsed copy.
const load = (name: string): Document => {
  const parsed = new DOMParser().parseFromString(readFileSync(`apps/extension/fixtures/${name}`, "utf8"), "text/html");
  document.documentElement.remove();
  document.appendChild(document.importNode(parsed.documentElement, true));
  return document;
};
const ARXIV = "https://arxiv.org/html/2106.09685";

const doc = load("arxiv-2106.09685.html");
const page = extractPage(doc, ARXIV);

describe("extractPage: arXiv", () => {

  it("reads the LaTeXML content, formulas as alttext, and nothing outside it", () => {
    expect(page.root.classList.contains("ltx_page_content")).toBe(true);
    expect(page.text).toContain("We apply LoRA to the attention weights");
    expect(page.text).toContain("W_0+BA");
    expect(page.text).not.toContain("navigation link");
    expect(page.text).not.toContain("Generated by LaTeXML");
  });

  it("tracks sections and the abstract's first sentence", () => {
    const intro = page.blocks.find((b) => page.text.slice(b.start, b.end).includes("We apply LoRA"))!;
    expect(intro.section).toBe("1 Introduction");
    expect(page.abstractFirstSentence).toBe(
      "We propose Low-Rank Adaptation, or LoRA, which freezes the pre-trained model weights and injects trainable rank decomposition matrices into each layer of the Transformer architecture.",
    );
  });

  it("maps text offsets back to DOM ranges, across inline elements", () => {
    const at = page.text.indexOf("LoRA to the attention");
    expect(rangeFor(page, at, at + 4)!.toString()).toBe("LoRA");
    const across = page.text.indexOf("Adapters add");
    expect(rangeFor(page, across, across + "Adapters add".length)!.toString()).toBe("Adapters add");
    expect(rangeFor(page, 5, 5)).toBeNull();
  });
});

describe("contextForRange", () => {
  const rangeOf = (setup: (r: Range) => void) => {
    const r = doc.createRange();
    setup(r);
    return r;
  };

  it("gives the paragraph, section and a quote selector for a word", () => {
    const ctx = contextForRange(page, rangeOf((r) => r.selectNodeContents(doc.getElementById("t-lora")!)))!;
    expect(ctx.selection).toBe("LoRA");
    expect(ctx.paragraph).toBe("Fine-tuning large models is expensive. We apply LoRA to the attention weights of the Transformer.");
    expect(ctx.section).toBe("1 Introduction");
    expect(ctx.locator.exact).toBe("LoRA");
    expect(ctx.locator.prefix.endsWith("We apply")).toBe(true);
    expect(ctx.locator.suffix.startsWith("to the attention")).toBe(true);
    expect(ctx.locator.section).toBe("1 Introduction");
  });

  it("uses both paragraphs when the selection spans two", () => {
    const intro = doc.getElementById("p-intro")!.firstChild!;
    const math = doc.getElementById("p-math")!.firstChild!;
    const ctx = contextForRange(page, rangeOf((r) => {
      r.setStart(intro, 0);
      r.setEnd(math, 6);
    }))!;
    expect(ctx.paragraph).toContain("Fine-tuning large models");
    expect(ctx.paragraph).toContain("The update is W_0+BA");
    const first = contextForRange(page, rangeOf((r) => r.selectNodeContents(doc.getElementById("t-lora")!)))!;
    expect(ctx.paragraphId).toBe(first.paragraphId);
  });

  it("handles a selection inside a formula", () => {
    const ctx = contextForRange(page, rangeOf((r) => r.selectNodeContents(doc.getElementById("m-w")!)))!;
    expect(ctx.selection).toBe("W");
    expect(ctx.paragraph).toContain("The update is W_0+BA where the rank is small.");
  });

  it("falls back to the nearest container for selections outside the content", () => {
    const nav = doc.querySelector("nav")!;
    const ctx = contextForRange(page, rangeOf((r) => r.selectNodeContents(nav)))!;
    expect(ctx.paragraph).toBe("Introduction navigation link");
    expect(ctx.paragraphId.startsWith("outside:")).toBe(true);
  });

  it("returns null for an empty selection", () => {
    expect(contextForRange(page, rangeOf((r) => r.setStart(doc.body, 0)))).toBeNull();
  });
});

describe("extractPage: other sites", () => {
  it("skips navigation, asides, scripts, styles, hidden elements and the extension's own hosts", () => {
    const doc = load("blog.html");
    const host = doc.createElement("div");
    host.textContent = "OverlayOnlyTerm";
    doc.querySelector("article")!.append(host);
    ownHosts.add(host);
    const page = extractPage(doc, "https://blog.example.com/posts/adapters");
    expect(page.text).toContain("Adapters are small modules");
    expect(page.text).toContain("LoRA is a popular adapter");
    expect(page.text).toContain("Prefix tuning is another option");
    for (const term of ["NavOnlyTerm", "AsideOnlyTerm", "ScriptOnlyTerm", "StyleOnlyTerm", "HiddenOnlyTerm", "InlineHiddenTerm", "ClassHiddenTerm", "FooterOnlyTerm", "OverlayOnlyTerm"]) {
      expect(page.text).not.toContain(term);
    }
    expect(page.abstractFirstSentence).toBe("A gentle introduction to adapters.");
  });
});

describe("firstSentence", () => {
  it("splits on Latin and CJK sentence ends", () => {
    expect(firstSentence("低秩适配。第二句。")).toBe("低秩适配。");
    expect(firstSentence("No end")).toBe("No end");
  });
});
